### PR TITLE
Allow install to be run when config file already exists

### LINKED ISSUE #17: Team members cannot run installation
A little oversight, but right now the installation script will check if `commit.exs` exists, and if it does, stops the execution of installation.

However, this means that let's say in a team of 3, if one person in the team installed, `commit.exs` will be git-tracked, now if it's pushed to repo and then the other two people pull it down, and try to run `mix committee.install` again, they won't run the git hooks installation part, because `commit.exs` exists.

Not quite sure what will be fix, maybe always run the git hooks installation? (but then this will override the backup). So ideally other team members should be able to run it.

Another idea I can think of is to create sort of like a "sentinel file". `commit.exs` should be that, but that's not enough because it's git-tracked, which means I need a gitignored version of sentinel file. Maybe could create a file inside `.git/hooks/committee.checksum` or something that acts as a sentinel, and run install if that file doesn't exist?

### PR DESCRIPTION
**Pull request by thiamsantos**
Closes #17

### CODE REVIEW

**Comment by thiamsantos** [comment]
@edisonywh Sorry for the delay on this PR, I was a little busy with other stuff, but finally I got some time to work on this. The idea is to change the installation process as was discussed at #17 .

The new flow would be something like this:

1 - If the commit.exs does not exist, create it.
2 - Reads all git hooks.
3 - For each git hook file.
3.1 - If it was generated by commitee, just skip the installation.
3.2 - If it was not generated by commitee continue.
3.3 - Backup the file, adding the .old prefix.
3.4 - Generate the hook using committee.

That will allow the install script to be run multiple times without messing up already installed hooks. Also allows the installation process to be run whenever we clone the repo, making possible for team members to also use the hooks.

I would love your feedback on this :)

**Comment by edisonywh** [comment]
Hey no worries on the delay, I haven't been putting as much time into this as I should've either!

I'm currently in midst of starting a new job so I don't have time to really look at it in depth yet, I'll get around to it as soon as possible (probably next week).

Sorry for the delay, and hope you had a great new year!

**Review by edisonywh — APPROVED** [review]
Great work @thiamsantos, thanks for taking the effort to do this, really appreciate it :)

I had previously tried out streaming the file by line and then checking line by line for the identifier and version, but it's apparent I've sort of overengineered a little, what you have currently works out really good 👍

**Comment by edisonywh** [comment]
The next thing on the roadmap then is to fix up the version as well! Thanks for the great work 🚀

**Pull request merged**
